//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ILEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ILEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap application_go {
            get {
                object obj = ResourceManager.GetObject("application_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADDACC|Add Access Code|2
        ///ADDAJE|Add Autostart Job Entry|2
        ///ADDALRACNE|Add Alert Action Entry|2
        ///ADDALRD|Add Alert Description|2
        ///ADDALRSLTE|Add Alert Selection Entry|2
        ///ADDASPCPYD|Add ASP Copy Description|2
        ///ADDAUTLE|Add Authorization List Entry|2
        ///ADDBKP|Add Breakpoint|2
        ///ADDBNDDIRE|Add Binding Directory Entry|2
        ///ADDCADMRE|Add Cluster Administrative Domain Managed Resource Entry|2
        ///ADDCADNODE|Add Cluster Administrative Domain Node Entry|2
        ///ADDCCSCLT|Add Change Control Server Client|2
        ///ADDCFGLE|Add Configu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, Helvetica, sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h3&gt;Compiling a program&lt;/h3&gt;
        ///    &lt;p&gt;IlEditor will compile most ILE types by default. To compile a program&lt;/p&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;Use the Compile dropdown when the member is open, or&lt;/li&gt;
        ///        &lt;li&gt;Right click on a member in the member listi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Compiling {
            get {
                return ResourceManager.GetString("Compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and|alternative to &amp;&amp; operator|6
        ///and_eq|alternative to &amp;= operator|6
        ///asm|insert an assembly instruction|6
        ///auto|declare a local variable, or we can let the compiler to deduce the type of the variable from the initialization.|6
        ///bitand|alternative to bitwise &amp; operator|6
        ///bitor|alternative to | operator|6
        ///bool|declare a boolean variable|6
        ///break|break out of a loop|6
        ///case|a block of code in a switch statement|6
        ///catch|handles exceptions from throw|6
        ///char|declare a character variable|6
        ///class|declare a c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CPP {
            get {
                return ResourceManager.GetString("CPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap firewall {
            get {
                object obj = ResourceManager.GetObject("firewall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, Helvetica, sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h3&gt;Something not working?&lt;/h3&gt;
        ///    &lt;p&gt;Are you seeing this error message?&lt;/p&gt;
        ///    &lt;img width=&quot;100%&quot; src=&quot;https://i.imgur.com/qA7Dhqt.png&quot; /&gt;
        ///    &lt;p&gt;This may be because the Windows Firewall is blocking either:&lt;/p&gt;
        ///    &lt;ul&gt;
        ///        &lt;li&gt;ftp.exe ( [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FTP {
            get {
                return ResourceManager.GetString("FTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, Helvetica, sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h3&gt;Library List in ILEditor&lt;/h3&gt;
        ///    &lt;p&gt;The library list will apply to every command sent from ILEditor, including all compiles. To open the library list editor:&lt;/p&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Select the Tools dropdown&lt;/li&gt;
        ///        &lt;li&gt;Select Librar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LibraryList {
            get {
                return ResourceManager.GetString("LibraryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, Helvetica, sans-serif;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h3&gt;Opening a specific member&lt;/h3&gt;
        ///    &lt;ol&gt;
        ///        &lt;li&gt;Select the File dropdown&lt;/li&gt;
        ///        &lt;li&gt;Select Open&lt;/li&gt;
        ///        &lt;li&gt;Select Member&lt;/li&gt;
        ///    &lt;/ol&gt;
        ///    &lt;p&gt;Or use the Ctrl+O shortcut to open the same window.&lt;/p&gt;
        ///
        ///    &lt;h3&gt;Opening a me [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OpenMember {
            get {
                return ResourceManager.GetString("OpenMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %ABS|Absolute Value of Expression|1
        ///%ADDR|Get Address of Variable|1
        ///%ALLOC|Allocate Storage|1
        ///%BITAND|Bitwise AND Operation|1
        ///%BITNOT|Invert Bits|1
        ///%BITOR|Bitwise OR Operation|1
        ///%BITXOR|Bitwise Exclusive-OR Operation|1
        ///%CHAR|Convert to Character Data|1
        ///%CHECK|Check Characters|1
        ///%CHECKR|Check Reverse|1
        ///%DATE|Convert to Date|1
        ///%DAYS|Number of Days|1
        ///%DEC|Convert to Packed Decimal Format|1
        ///%DECH|Convert to Packed Decimal Format with Half Adjust|1
        ///%DECPOS|Get Number of Decimal Positions|1
        ///%DIFF|D [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RPG {
            get {
                return ResourceManager.GetString("RPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap script_add {
            get {
                object obj = ResourceManager.GetObject("script_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap script_go {
            get {
                object obj = ResourceManager.GetObject("script_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
